### ISSUE TITLE
Unable to create source for Azure account using Connect with Single Registration

### ISSUE THREAD

**Issue by lucas-benedito** [RedHatInsights/ansible-collection-subscriptions#4]
We have a couple of cases where the customer is unable to create a source with the single registration on the https://cloud.redhat.com [Hybrid Cloud Console].

This issue was also registered in TEAMNADO-2616.

Error:
~~~
TASK [redhatinsights.subscriptions.auto_registration_verification : create verified cloud provider account] *******************************
task path: /home/username/.ansible/collections/ansible_collections/redhatinsights/subscriptions/roles/auto_registration_verification/tasks/verify.yml:3
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: username
<localhost> EXEC /bin/sh -c 'echo ~username && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/username/.ansible/tmp `"&& mkdir "` echo /home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896 `" && echo ansible-tmp-1641548600.2290578-185438-205050128979896="` echo /home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896 `" ) && sleep 0'
Using module file /home/username/.ansible/collections/ansible_collections/redhatinsights/subscriptions/plugins/modules/cloud_provider_account.py
<localhost> PUT /home/username/.ansible/tmp/ansible-local-184829xqm3o0hc/tmptrx3xx2c TO /home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/AnsiballZ_cloud_provider_account.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/ /home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/AnsiballZ_cloud_provider_account.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/libexec/platform-python /home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/AnsiballZ_cloud_provider_account.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/AnsiballZ_cloud_provider_account.py", line 102, in <module>
    _ansiballz_main()
  File "/home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/AnsiballZ_cloud_provider_account.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/AnsiballZ_cloud_provider_account.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.redhatinsights.subscriptions.plugins.modules.cloud_provider_account', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_redhatinsights.subscriptions.cloud_provider_account_payload_sf_lwwv_/ansible_redhatinsights.subscriptions.cloud_provider_account_payload.zip/ansible_collections/redhatinsights/subscriptions/plugins/modules/cloud_provider_account.py", line 207, in <module>
  File "/tmp/ansible_redhatinsights.subscriptions.cloud_provider_account_payload_sf_lwwv_/ansible_redhatinsights.subscriptions.cloud_provider_account_payload.zip/ansible_collections/redhatinsights/subscriptions/plugins/modules/cloud_provider_account.py", line 203, in main
  File "/tmp/ansible_redhatinsights.subscriptions.cloud_provider_account_payload_sf_lwwv_/ansible_redhatinsights.subscriptions.cloud_provider_account_payload.zip/ansible_collections/redhatinsights/subscriptions/plugins/modules/cloud_provider_account.py", line 130, in run_module
TypeError: 'NoneType' object is not iterable
fatal: [hostname]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/AnsiballZ_cloud_provider_account.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/AnsiballZ_cloud_provider_account.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/username/.ansible/tmp/ansible-tmp-1641548600.2290578-185438-205050128979896/AnsiballZ_cloud_provider_account.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.redhatinsights.subscriptions.plugins.modules.cloud_provider_account', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_redhatinsights.subscriptions.cloud_provider_account_payload_sf_lwwv_/ansible_redhatinsights.subscriptions.cloud_provider_account_payload.zip/ansible_collections/redhatinsights/subscriptions/plugins/modules/cloud_provider_account.py\", line 207, in <module>\n  File \"/tmp/ansible_redhatinsights.subscriptions.cloud_provider_account_payload_sf_lwwv_/ansible_redhatinsights.subscriptions.cloud_provider_account_payload.zip/ansible_collections/redhatinsights/subscriptions/plugins/modules/cloud_provider_account.py\", line 203, in main\n  File \"/tmp/ansible_redhatinsights.subscriptions.cloud_provider_account_payload_sf_lwwv_/ansible_redhatinsights.subscriptions.cloud_provider_account_payload.zip/ansible_collections/redhatinsights/subscriptions/plugins/modules/cloud_provider_account.py\", line 130, in run_module\nTypeError: 'NoneType' object is not iterable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
~~~

The following workaround appears to work for some cases:
~~~
# ansible-playbook -i XX.XX.XX.XXX, -u azureuser -b ~/.ansible/collections/ansible_collections/redhatinsights/subscriptions/playbooks/verify_account.yml -e rh_api_refresh_token=[token]
~~~

**Comment by dc-chris-smith** [comment]
I too am receiving the same error.  Just to be sure I tried all possibilities, I ran it with the base ansible version of 2.9.25 and also under 2.10.15 in a vnenv.  I even deployed a brand new VM using the 8.4 LVM image and it still failed with "NonType object is not iterable."  I've even verified that requests-oauthlib was installed already.

**Comment by jdelaporte** [comment]
I am not sure if I am running into the same problem, since I am getting a different error.  I am not able to make my Linux VM on Azure run the last verify step. I get the error that the requests-oauthlib package is required. That package is installed and visible to other modules only if I set the environment var for PATH to include /usr/local/lib.  Ansible can find the pip3 package, but not the pip package, until I set the PATH env var. However, it still fails for the verify step, even if I set the env var for that task.

```

TASK [redhatinsights.subscriptions.auto_registration_verification : Get pip command path] ********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "which pip", "delta": "0:00:00.005631", "end": "2023-01-12 23:44:16.155952", "msg": "non-zero return code", "rc": 1, "start": "2023-01-12 23:44:16.150321", "stderr": "which: no pip in (/sbin:/bin:/usr/sbin:/usr/bin)", "stderr_lines": ["which: no pip in (/sbin:/bin:/usr/sbin:/usr/bin)"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [redhatinsights.subscriptions.auto_registration_verification : print requests-oauthlib version] *********************************************************************************************************************************
ok: [localhost] => {
    "msg": "pip3 oauthlib_version is 1.3.1  \npip oauthlib_version is /bin/sh: pip: command not found  \npip3 path is /bin/pip3        \npip path is which: no pip in (/sbin:/bin:/usr/sbin:/usr/bin)\n"
}

TASK [redhatinsights.subscriptions.auto_registration_verification : create verified cloud provider account] **************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "This module requires the python 'requests-oauthlib' package. Try `pip install requests-oauthlib`."}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=1    skipped=15   rescued=0    ignored=1   
```

My VM on Azure:

```
 [azureuser@CloudAccess4 ~]$ ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Sep 10 2021, 09:13:53) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]. This feature will be 
removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
/home/azureuser/.local/lib/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.exceptions import InvalidSignature
ansible [core 2.11.12] 
  config file = None
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/azureuser/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/azureuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/azureuser/.local/bin/ansible
  python version = 3.6.8 (default, Sep 10 2021, 09:13:53) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.1
  libyaml = True
[azureuser@CloudAccess4 ~]$ cat /etc/redhat-release 
CentOS Linux release 8.5.2111
```

I used these additional tasks to diagnose whether Ansible could find the requests-oauthlib package
```
- name: Get pip3 version of requests-oauthlib
  shell: pip3 show requests-oauthlib | grep Version | cut -d ' ' -f 2
  ignore_errors: True
  changed_when: false
  register: pip3_oauthlib_version

- name: Get pip version of requests-oauthlib
  shell: pip show requests-oauthlib | grep Version | cut -d ' ' -f 2
  ignore_errors: True
  changed_when: false
  register: pip_oauthlib_version

- name: Get pip3 command path
  shell: which pip3
  ignore_errors: True
  changed_when: false
  register: pip3_command_path

- name: Get pip command path
  shell: which pip
  ignore_errors: True
  changed_when: false
  register: pip_command_path

- name: print requests-oauthlib version
  debug:
    msg: |
            pip3 oauthlib_version is {{ pip3_oauthlib_version.stdout|default(pip3_oauthlib_version.stderr, true) }}  
            pip oauthlib_version is {{ pip_oauthlib_version.stdout |default(pip_oauthlib_version.stderr, true) }}  
            pip3 path is {{ pip3_command_path.stdout|default(pip3_command.stderr, true) }}        
            pip path is {{ pip_command_path.stdout | default(pip_command.stderr, true) }}
```

**Comment by gonoph** [comment]
> I am not sure if I am running into the same problem, since I am getting a different error. I am not able to make my Linux VM on Azure run the last verify step. I get the error that the requests-oauthlib package is required. That package is installed and visible to other modules only if I set the environment var for PATH to include /usr/local/lib. 
> Ansible can find the pip3 package, but not the pip package, until I set the PATH env var. However, it still fails for the verify step, even if I set the env var for that task.

Hey there.

So, not sure if you were able to resolve this, but I figured I would help clarify some behaviors.

pip vs pip3 is a red herring issue. pip or pip3 is just the command used to install the package from the pypi repositories. Some distros (and users) make an alias for pip to pip$python_major_version - whatever that may be. It's a nice-to-have, but not really a requirement. For the most part, python devs are getting used to giving the major version of the python things they want ever since the python 2 to 3 migration wars.

So this leaves the Q of why can't ansible see that package?

It goes back to not only HOW you installed it from pip (or pip3), but WHERE it was installed.

If you install it from pip as user root - then by default, it's going to put it in `/usr/local/lib` - which is not a default "python path" for Ansible.

If you install it as a normal user with

```bash
pip install --user $package
```

then it's a little better, but I have some suggestions that Work Every Time(tm).

1. Use a [python virtual environment][1] for your command line ansible playbooks.
2. run as a non-root user

[1]: https://docs.python.org/3/library/venv.html

By using a python venv:

1. you're essentially isolating your ansible playbook environment from all the "other python stuff" that might be on the host.
2. it also ensures that anything you install from pip inside that environment goes into the right directory.
3. and ansible being ran while in that python environment also knows the right directories to find the stuff pip installed.
4. making it WAY easier for you to one day move those playbooks to AWX or Ansible Automation Platform.

Following that guide, once you create that python venv, you just activate it using the examples in the guide, use pip to install the things you need, and then run ansible against the playbook you want.

I hope this helps!
